<a href="https://colab.research.google.com/github/anshulsawant/WhatDoesThisReallyDo/blob/main/What_does_this_function_really_do_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## My attempt to address my biggest numpy fear: I assume that this function is processing stuff in some way, but what if it isn't. I hope this is not going to come crashing down.

import numpy as np

In [10]:
## What does reshape REALLY do
x = np.arange(24)
print(x)
print(x.reshape((2,3,4), order='C')) ## last index changing fastest (default)
print(x.reshape((2,3,4), order='F')) ## first index changing fastest
print(x.reshape((2,3,4)).reshape((2,3,2,2)))
print(x.reshape((2,3,4)).reshape((2,3,2,2), order='F'))
## From numpy docs
## The order keyword gives the index ordering both for fetching the values from a, and then placing the values into the output array. For example, let’s say you have an array:
## You can think of reshaping as first raveling the array (using the given index order), then inserting the elements from the raveled array into the new array using the same kind of index ordering as was used for the raveling.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
[[[[ 0  2]
   [ 1  3]]

  [[ 4  6]
   [ 5  7]]

  [[ 8 10]
   [ 9 11]]]


 [[[12 14]
   [13 15]]

  [[16 18]
   [17 19]]

  [[20 22]
   [21 23]]]]
